# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-18 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='posts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
    ]
