# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-19 18:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.RemoveField(
            model_name='people',
            name='posts',
        ),
        migrations.DeleteModel(
            name='People',
        ),
    ]
