# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-30 07:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_mymodel_people'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.RemoveField(
            model_name='people',
            name='posts',
        ),
        migrations.DeleteModel(
            name='People',
        ),
    ]
